AllCops:
  TargetRubyVersion:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/{rails,rake}'
    - 'test/**/*'
    - "gemfiles/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Max: 30

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Style/Documentation:
  Enabled: false
